alter pluggable database KEO_PDB open;

grant create trigger to keo;


--1----------------------------------------------------------`

create table BANK(
user_id number generated by default as identity primary key,
name nvarchar2(50) not null, 
balance number(10,2) default 0 check(balance >=0)
);

drop table BANK purge;


--2----------------------------------------------------------

insert into bank(name, balance) values ('Алексей', 1000);
insert into bank(name, balance) values ('Владимир', 100000);
insert into bank(name, balance) values ('Владислав', 20);
insert into bank(name, balance) values ('Анна', 100);
insert into bank(name, balance) values ('Анастасия', 300);
insert into bank(name, balance) values ('Михаил', 15);
insert into bank(name, balance) values ('Дарья', 2000);
insert into bank(name, balance) values ('Александр', 30000);
insert into bank(name, balance) values ('Павел', 1);
insert into bank(name, balance) values ('Николай', 2);
commit;
delete BANK;

select * from bank;

--3-----------------------------------------------------------------

create or replace trigger OPERATOR_BEFORE_ALL
before insert or update or delete on bank
begin
 if inserting then 
        dbms_output.put_line('inserting триггер OPERATOR_BEFORE_ALL');
    elsif updating then
        dbms_output.put_line('updating триггер OPERATOR_BEFORE_ALL');
    elsif deleting then 
        dbms_output.put_line('deleting триггер OPERATOR_BEFORE_ALL');
    end if;
end;


--5-6-----------------------------------------------------------------

create or replace trigger ROW_BEFORE_ALL
before insert or update or delete on bank
for each row
begin
    if inserting then 
        dbms_output.put_line('inserting триггер ROW_BEFORE_ALL');
    elsif updating then
        dbms_output.put_line('updating триггер ROW_BEFORE_ALL');
    elsif deleting then 
        dbms_output.put_line('deleting триггер ROW_BEFORE_ALL');
    end if;
end;

--7-----------------------------------------------------------------

create or replace trigger OPERATOR_AFTER_ALL
before insert or update or delete on bank
begin
dbms_output.put_line('Триггер OPERATOR_AFTER_ALL');

end;

--8-------------------------------------------------------------

create or replace trigger ROW_AFTER_ALL
before insert or update or delete on bank
for each row
begin
    if inserting then 
        dbms_output.put_line('inserting триггер OPERATOR_AFTER_ALL');
    elsif updating then
        dbms_output.put_line('updating триггер OPERATOR_AFTER_ALL');
    elsif deleting then 
        dbms_output.put_line('deleting триггер OPERATOR_AFTER_ALL');
    end if;
end;


--9-------------------------------------------------------------------


create table AUDIT_LOG(
operationDate Date,
operationType varchar2(10),
triggerName varchar2(20),
Data varchar2(100)
);

drop table audit_log purge;

--10------------------------------------------------------------------

create or replace trigger operator_before_all
before insert or update or delete on bank
declare
    operation audit_log.operationtype%type;
begin
    if inserting then
        operation := 'insert';
    elsif updating then
        operation := 'update';
    elsif deleting then
        operation := 'delete';
    end if;
     dbms_output.put_line('триггер OPERATOR_BEFORE_ALL');
    insert into audit_log values(sysdate, operation, 'operator_before_all', null);    
end;


create or replace trigger row_before_all
before insert or update or delete on bank
for each row
declare
    operation audit_log.operationtype%type;
    data audit_log.data%type;
begin
 if inserting then 
        operation := 'insert';
        data := :new.user_id || :new.name || :new.balance;
        dbms_output.put_line('inserting триггер ROW_BEFORE_ALL');
    elsif updating then
    operation := 'update';
    data := :old.user_id || :old.name || :old.balance || ':' || :new.user_id || :new.name || :new.balance;
        dbms_output.put_line('updating триггер ROW_BEFORE_ALL');
    elsif deleting then 
     data := :old.user_id || :old.name || :old.balance;
     operation := 'delete';
        dbms_output.put_line('deleting триггер ROW_BEFORE_ALL');
    end if;
    
    insert into audit_log values (sysdate, operation, 'row_before_all', data);
end;


create or replace trigger operator_after_all
before insert or update or delete on bank
declare
    operation audit_log.operationtype%type;
begin
    if inserting then
        operation := 'insert';
    elsif updating then
        operation := 'update';
    elsif deleting then
        operation := 'delete';
    end if;
     dbms_output.put_line('триггер OPERATOR_AFTER_ALL');
    insert into audit_log values(sysdate, operation, 'operator_after_all', null);    
end;



create or replace trigger row_after_all
after insert or update or delete on bank
for each row
declare
    operation audit_log.operationtype%type;
    data audit_log.data%type;
begin
 if inserting then 
        operation := 'insert';
        data := :new.user_id || :new.name || :new.balance;
        dbms_output.put_line('inserting триггер ROW_AFTER_ALL');
    elsif updating then
    operation := 'update';
    data := :old.user_id || :old.name || :old.balance || ':' || :new.user_id || :new.name || :new.balance;
        dbms_output.put_line('updating триггер ROW_AFTER_ALL');
    elsif deleting then 
     data := :old.user_id || :old.name || :old.balance;
     operation := 'delete';
        dbms_output.put_line('deleting триггер ROW_AFTER_ALL');
    end if;
   
    insert into audit_log values (sysdate, operation, 'row_after_all', data);
end;



--11------------------------------------------------------------

delete audit_log;

select * from audit_log;
delete bank;

insert into bank values (1, 'Дмитрий', 1);

--12----------------------------------------------------------

drop table bank purge;
drop trigger tr_drop_table;

create or replace trigger tr_drop_table
before drop on schema
begin
    if (ORA_DICT_OBJ_NAME = 'BANK') then
        raise_application_error(-20000, 'Didnt drop ' || ORA_DICT_OBJ_TYPE || ' ' || ORA_DICT_OBJ_NAME);
    end if;
end;


--13----------------------------------------------------------

alter trigger operator_before_all compile;
alter trigger row_before_all compile;
alter trigger operator_after_all compile;
alter trigger row_after_all compile;


drop table AUDIT_LOG;
flashback table AUDIT_LOG to before drop;

--14---------------------------------------------------------


drop view vBank;

create view vBank as
select user_id, name, balance from BANK;


create or replace trigger instead_trigger
instead of update or insert or delete on vBANK
declare
    data varchar2(100);
begin
    data := :new.user_id || :new.name || :new.balance;
   -- insert into audit_log values(sysdate, 'insert', 'instead_trigger', data);
    
    
    if(:new.user_id is null) then 
        insert into BANK(name, balance) values ( :new.name, :new.balance);
    else
        insert into BANK values (:new.user_id, :new.name, :new.balance);
    end if;
    
end;


insert into vBANK(name, balance) values ('Алекс', 10000);

select * from bank
